name: supa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  fl_chart: ^0.69.0
  image_picker: ^1.0.7
  lottie: ^3.3.2
  supabase_flutter: ^2.12.0
  google_fonts: ^8.0.0
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.7
  url_launcher: ^6.3.1
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.0
  animations: ^2.1.1
  skeletonizer: ^2.1.3
  connectivity_plus: ^7.0.0
  flutter_animate: ^4.5.2
  local_auth: ^2.1.6
  local_auth_android: ^1.0.32
  local_auth_darwin: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/animations/
    - assets/icon/
    - assets/translations/en.json
    - assets/translations/ru.json
    - assets/translations/tk.json

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"

